In [ ]:
import numpy as np

In [ ]:
class ANDNN(object):
  def __init__(self):
    self.W = np.ones((2,1))
    self.b = -2
  def forward(self,X):
    self.yHat = X@self.W + self.b
    return self.activation(self.yHat)
  def activation(self,z):
    for i in range(len(z)):
      if z[i] >= 0:
        z[i] = 1
      else:
        z[i]=0
    return z
  def cost(self,X,y):
    yHat = self.forward(X)
    return 1/2*(yHat - y)**2


In [ ]:
X = np.array([[0,0,0],[0,0,1],[0,1,0],[1,0,0],[0,1,1],[1,0,1],[1,1,0],[1,1,1]])

In [ ]:
X1 = [[0,0],[0,1],[1,0],[1,1]]

In [ ]:
nn = ANDNN()

In [ ]:
yHat = nn.forward(X1)

In [ ]:
yHat

array([[0.],
       [0.],
       [0.],
       [1.]])

In [ ]:
class XORNN(object):
  def __init__(self):
    self.W = np.ones((2,1))
    self.b = -1
  def forward(self,X):
    self.yHat = X@self.W + self.b
    return self.activation(self.yHat)
  def activation(self,z):
    for i in range(len(z)):
      if z[i] != 0:
        z[i] = 0
      else:
        z[i] = 1
    return z
  def cost(self,X,y):
    yHat = self.forward(X)
    return 1/2*(yHat - y)**2

In [ ]:
nnn = XORNN()

In [ ]:
yHHat = nnn.forward(X1)

In [ ]:
yHHat

array([[0.],
       [1.],
       [1.],
       [0.]])

In [ ]:
#Full Adder using XOR and AND
class FullAdder(object):
  def __init__(self):
    self.XOR = XORNN()
    self.AND = ANDNN()

  def forward(self,X):
    return np.hstack((self.XOR.forward(np.hstack((self.XOR.forward(X[:,:2]),X[:,2:3]))),self.XOR.forward(np.hstack((self.AND.forward(X[:,:2]),self.AND.forward(np.hstack((self.XOR.forward(X[:,:2]),X[:,2:3]))))))))

  def forward(self, a, b, c):
    sum = self.XOR.forward(np.hstack((self.XOR.forward([a,b]),c)))
    carry = self.XOR.forward(np.hstack((self.AND.forward([a,b]),self.AND.forward(np.hstack((self.XOR.forward([a,b]),c))))))
    return sum[0], carry[0]

In [ ]:
yHat = FullAdder().forward(X)

In [ ]:
yHat

array([[0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.]])

In [ ]:
s,c = FullAdder().forward(1,1,0)

In [ ]:
s,c

(0.0, 1.0)

In [68]:
#Ripple Carry Adder
class rippleCarryAdder(object):
  def __init__(self):
    self.FA = FullAdder()
  def forward(self,X,Y):
    X = np.array(X)
    X = np.flip(X)
    Y = np.array(Y)
    Y = np.flip(Y)
    Z = np.zeros((max(len(X),len(Y))+1))
    if(len(X) < len(Y)):
      X = np.pad(X,len(Y)-len(X))
    elif(len(X) > len(Y)):
      Y = np.pad(Y,len(X)-len(Y))
    s,c = self.FA.forward(X[0],Y[0],0)
    Z[0] = s
    for i in range(max(len(X),len(Y))-1):
      s,c = self.FA.forward(X[i+1],Y[i+1],c)
      Z[i+1] = s
    Z[-1] = c
    return np.flip(Z)

In [70]:
rippleCarryAdder().forward([1,1,1],[1,0,0])

array([1., 0., 1., 1.])