In [33]:
import numpy as np

In [34]:
class ANDNN(object):
  def __init__(self):
    self.W = np.ones((2,1))
    self.b = -2
  def forward(self,X):
    self.yHat = X@self.W + self.b
    return self.activation(self.yHat)
  def activation(self,z):
    for i in range(len(z)):
      if z[i] >= 0:
        z[i] = 1
      else:
        z[i]=0
    return z
  def cost(self,X,y):
    yHat = self.forward(X)
    return 1/2*(yHat - y)**2


In [35]:
X = np.array([[0,0,0],[0,0,1],[0,1,0],[1,0,0],[0,1,1],[1,0,1],[1,1,0],[1,1,1]])

In [36]:
X1 = [[0,0],[0,1],[1,0],[1,1]]

In [37]:
nn = ANDNN()

In [38]:
yHat = nn.forward(X1)

In [39]:
yHat

array([[0.],
       [0.],
       [0.],
       [1.]])

In [40]:
class XORNN(object):
  def __init__(self):
    self.W = np.ones((2,1))
    self.b = -1
  def forward(self,X):
    self.yHat = X@self.W + self.b
    return self.activation(self.yHat)
  def activation(self,z):
    for i in range(len(z)):
      if z[i] != 0:
        z[i] = 0
      else:
        z[i] = 1
    return z
  def cost(self,X,y):
    yHat = self.forward(X)
    return 1/2*(yHat - y)**2

In [41]:
nnn = XORNN()

In [42]:
yHHat = nnn.forward(X1)

In [43]:
yHHat

array([[0.],
       [1.],
       [1.],
       [0.]])

In [44]:
#Full Adder using XOR and AND
class FullAdder(object):
  def __init__(self):
    self.XOR = XORNN()
    self.AND = ANDNN()

  def forward(self,X):
    return np.hstack((self.XOR.forward(np.hstack((self.XOR.forward(X[:,:2]),X[:,2:3]))),self.XOR.forward(np.hstack((self.AND.forward(X[:,:2]),self.AND.forward(np.hstack((self.XOR.forward(X[:,:2]),X[:,2:3]))))))))


In [45]:
yHat = FullAdder().forward(X)

In [46]:
yHat

array([[0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.]])